import { Resend } from 'resend'

const resend = new Resend(process.env.RESEND_API_KEY)

function credentialEmailHtml({ name, username, password, role, assemblyName, isRegenerated }) {
  const roleLabel = {
    GLOBAL_ADMIN: 'Global Admin',
    SITE_CONTENT_ADMIN: 'Site Content Admin',
    ASSEMBLY_ADMIN: 'Assembly Admin',
    APP_ADMIN: 'App Admin',
  }[role] || role

  const action = isRegenerated ? 'Your credentials have been reset' : 'Your admin account has been created'
  const intro = isRegenerated
    ? 'Your login credentials have been regenerated by a global administrator. Use the details below to sign in.'
    : 'Welcome to Destiny Mission Global Assembly Admin Portal. Your account is ready. Use the details below to sign in.'

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>${action}</title>
</head>
<body style="margin:0;padding:0;background:#f5f0eb;font-family:'Segoe UI',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f5f0eb;padding:32px 16px;">
    <tr><td align="center">
      <table width="100%" style="max-width:520px;background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08);">

        <!-- Header -->
        <tr>
          <td style="background:#3b0764;padding:32px 40px;text-align:center;">
            <p style="margin:0;font-size:11px;letter-spacing:3px;text-transform:uppercase;color:rgba(255,255,255,0.5);">Destiny Mission Global Assembly</p>
            <h1 style="margin:12px 0 0;font-size:22px;font-weight:700;color:#ffffff;">${action}</h1>
          </td>
        </tr>

        <!-- Body -->
        <tr>
          <td style="padding:36px 40px;">
            <p style="margin:0 0 8px;font-size:15px;color:#374151;">Hello <strong>${name}</strong>,</p>
            <p style="margin:0 0 28px;font-size:14px;color:#6b7280;line-height:1.6;">${intro}</p>

            <!-- Credentials box -->
            <table width="100%" cellpadding="0" cellspacing="0" style="background:#faf7ff;border:1px solid #e9d5ff;border-radius:12px;margin-bottom:28px;">
              <tr><td style="padding:24px 28px;">
                <p style="margin:0 0 16px;font-size:11px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#7c3aed;">Login Credentials</p>

                <table width="100%" cellpadding="0" cellspacing="0">
                  <tr>
                    <td style="padding:8px 0;border-bottom:1px solid #ede9f7;font-size:13px;color:#6b7280;width:40%;">Username</td>
                    <td style="padding:8px 0;border-bottom:1px solid #ede9f7;font-size:13px;font-weight:700;color:#1f2937;font-family:monospace;">${username}</td>
                  </tr>
                  <tr>
                    <td style="padding:8px 0;border-bottom:1px solid #ede9f7;font-size:13px;color:#6b7280;">Password</td>
                    <td style="padding:8px 0;border-bottom:1px solid #ede9f7;font-size:13px;font-weight:700;color:#1f2937;font-family:monospace;">${password}</td>
                  </tr>
                  <tr>
                    <td style="padding:8px 0;border-bottom:1px solid #ede9f7;font-size:13px;color:#6b7280;">Role</td>
                    <td style="padding:8px 0;border-bottom:1px solid #ede9f7;font-size:13px;color:#1f2937;">${roleLabel}</td>
                  </tr>
                  ${assemblyName ? `<tr>
                    <td style="padding:8px 0;font-size:13px;color:#6b7280;">Assembly</td>
                    <td style="padding:8px 0;font-size:13px;color:#1f2937;">${assemblyName}</td>
                  </tr>` : ''}
                </table>
              </td></tr>
            </table>

            <p style="margin:0 0 20px;font-size:13px;color:#6b7280;line-height:1.6;">
              For security, you will be asked to change your password on first login.
              Keep these credentials safe and do not share them.
            </p>

            <!-- CTA -->
            <table cellpadding="0" cellspacing="0" style="margin:0 auto 28px;">
              <tr><td style="background:#3b0764;border-radius:8px;">
                <a href="${process.env.NEXTAUTH_URL || 'https://destinymissionglobal.org'}/admin/login"
                   style="display:inline-block;padding:12px 28px;font-size:14px;font-weight:600;color:#ffffff;text-decoration:none;">
                  Sign In to Admin Portal →
                </a>
              </td></tr>
            </table>
          </td>
        </tr>

        <!-- Footer -->
        <tr>
          <td style="padding:20px 40px;background:#fafafa;border-top:1px solid #f0f0f0;text-align:center;">
            <p style="margin:0;font-size:11px;color:#9ca3af;">
              This is an automated message from Destiny Mission Global Assembly Admin System.<br/>
              If you did not expect this email, please contact your administrator.
            </p>
          </td>
        </tr>

      </table>
    </td></tr>
  </table>
</body>
</html>`
}

/**
 * Send login credentials to an admin via email.
 * Silently skips if RESEND_API_KEY is not configured or no email provided.
 */
export async function sendCredentialEmail({ to, name, username, password, role, assemblyName, isRegenerated = false }) {
  if (!to || !process.env.RESEND_API_KEY) return

  const fromName = process.env.RESEND_FROM_NAME || 'DMGA Admin'
  const fromEmail = process.env.RESEND_FROM_EMAIL || 'noreply@destinymissionglobal.org'

  const subject = isRegenerated
    ? 'Your DMGA Admin Credentials Have Been Reset'
    : 'Your DMGA Admin Account Is Ready'

  try {
    await resend.emails.send({
      from: `${fromName} <${fromEmail}>`,
      to,
      subject,
      html: credentialEmailHtml({ name, username, password, role, assemblyName, isRegenerated }),
    })
  } catch (err) {
    // Log but never throw — email failure should not break the API response
    console.error('[EMAIL] Failed to send credential email:', err.message)
  }
}
